spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/music_player_db
    username: postgres
    password: postgres
  jpa:
    show-sql: false
    open-in-view: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
app:
  api_base_url: /v1
  jwt-secret: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
  jwt-refresh-secret: IPA32lUb6_SJpWJONVmYPMtzYcXRab1QI3EziPzU4pU
  jwt-expiration: 7200000
  jwt-refresh-expiration: 840000

springdoc:
  api-docs:
    groups:
      enabled: true
  group-configs:
    - group: User Authentication API
      display-name: User Authentication API
      paths-to-match: /v1/auth/**
      packages-to-scan:
        - "com.example.music_player.auth"
    - group: Music Player API
      display-name: Music Player API
      paths-to-match: /v1/**
      packages-to-scan:
        - "com.example.music_player"
aws:
  s3:
    access-key: AKIAW5WU5IZ4EKCDKR6P
    secret-key: 9mrlj+oiRoJ5/7W9XO0E1UlJxN+lexBS9CdVcHTn
    region: eu-north-1
    bucket-name: mymusicsbucket
